apiVersion: v1
kind: Pod
metadata:
  name: volume-pod1
  labels:
    name: volume-pod1
spec:
  volumes:
    - name: vol1

  containers:
  - name: myapp
    image: nginx:1.7.9
    volumeMounts:
      - name: vol1
        mountPath: "/data"
        readOnly: false
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
