apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    name: cm-pod
spec:
  containers:
  - name: cm-pod
    image: nginx:1.7.9
    ### Setting ENVIRONMENT variables
    env:
    - name: MYNAME
      value: MAHENDRA
    ### IMPORTING ENVIRONMENT variable from configmap
    envFrom:
    - configMapRef:
        name: myconfig
    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
