apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      ### Increase the ORIGINAL REPLICA COUNT by ONE 
      maxSurge: 1
      ### CAN'T AFFORD MORE THAN ONE INSTANCE DOWN!
      maxUnavailable: 1
  ## Wait for 3 Seconds after POD is created!
  minReadySeconds: 3
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web
        image: nginx:1.11.1
        ports:
        - containerPort: 80
