apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc1
spec:
  ## Define number of instances
  replicas: 3
  selector:
  ## Identify which PODS should be part of this Set
    matchLabels:
      name: myapp
  template: # Begining of POD Template
    metadata:
    ## define name of POD (Must MATCH with Line# 10 )
      name: myapp
      labels: # Must match with matchLabels in line 11
        name: myapp
    spec:
      containers:
        - image: nginx:1.7.9
          name: web
          ports:
            - containerPort: 80

