## Service for POD1
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ## Service type: LoadBalancer (External), NodePort, ClusterIp
  type: LoadBalancer
  ## Pick PODS using LABELS
  selector:
    app: app1
  ports:
  ## Service port
  - port: 8080
  ## Port on Containers (EndPoint)
    targetPort: 3000

