version: "3"

services:
  app:
    image: nginx
    ports: 
      - "80"
    networks: 
      - net1

networks: 
  net1:
    driver: bridge
    ipam:
      config:
      - subnet: "190.10.0.0/16"  

  